var poi = {
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [


{ "type": "Feature", "properties": { "id": "ARTBOU0210021133", "nom": "Eglise Saint Germain", "descriptif": "Édifice central du village durant des siècles, l’église est située à l’intersection des voies de circulation et au bord de la rivière. Datant du XI siècle, notre église a subi des modifications architecturales au cours des ans, les traces en ont été mises en évidence lors des travaux de restauration. L’église a été préservée d’éventuelles dégradations durant la période révolutionnaire grâce à un personnage important de notre village, le Père Jean Arnaud De Clamane. Nommé prêtre à Condé en 1789, sous le nom de Père Arnaud, il prête le serment civique en reprenant son nom entier, il est élu rédacteur des actes d’état civil et membre du Conseil général de la Commune de Condé. Il est maire de Condé jusqu’à son décès en 1806, il est enterré au cimetière de Condé. L’église n’a plus de prêtre depuis 1807 suite au Concordat. Elle est érigée en chapelle le 21 mars 1891 suite à de nombreuses et insistantes requêtes des villageois auprès de l’évêché de Versailles.", "tel": null, "mail": null, "site_web": "", "sous_cat": "Patrimoine religieux", "categorie": "Patrimoine", "adresse": null, "adresse2": "", "cp": null, "commune": null, "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [1.6616230884029908,48.74248243106098  ] } },

{ "type": "Feature", "properties": { "id": "ARTBOU0210021135", "nom": "Lavoir", "descriptif": "Les épidémies de typhoïde, de variole et de choléra du 19ème siècle, contraignent les villages à modifier les habitudes des femmes qui jusque-là, lavent le linge indifféremment à la rivière, à la fontaine ou à la mare. Il faut donc créer des lieux de lavage pour concentrer les eaux souillées en un endroit. Elles ne sont plus mélangées aux eaux de la fontaine ou de la mare, utilisables pour les autres tâches domestiques. C’est en 1851 que l’Etat attribue des subventions aux villes et villages pour installer des lavoirs et ainsi réaliser un grand progrès dans l’hygiène individuelle et la santé publique. Les grandes propriétés et les exploitations agricoles importantes, notamment en raison du nombre de personnel en place, avaient leur lavoir. Le lavoir encore visible, capte l’eau d’une source qui sourd depuis le fond de son bassin.", "	tel": null, "mail": null, "site_web": "", "sous_cat": "Patrimoine Remarquable", "categorie": "Patrimoine", "adresse" : "", "adresse2": "", "cp": "", "commune": "", "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6630801637161252,48.74307151303044 ] } },
{ "type": "Feature", "properties": { "id": "ARTBOU0210021136", "nom": "Des prés à l'assiette", "descriptif": "Heures d'ouverture : Mercredi et Jeudi de 10h30 à 19h00, Vendredi 8h30 à 19h, Samedi de 8h30 à 19h30 et Dimanche de 8h30 à 13h", "tel": "", "mail": null, "site_web": "", "sous_cat": "Alimentaire", "categorie": "Commerces", "adresse" : "", "adresse2": "", "cp": "", "commune": "", "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.6578071372203167 ,48.74148346623581 ] } },
{ "type": "Feature", "properties": { "id": "ARTBOU0210021137", "nom": "Boulangerie Fortier", "descriptif": "Heures d'ouverture : du Mardi au Samedi de 7h30 à 13h30 et de 15h à 19h30 et le Dimanche de 7h à 13h30", "tel": "", "mail": null, "site_web": "", "sous_cat": "Boulanger", "categorie": "Commerces", "adresse" : "", "adresse2": "", "cp": "", "commune": "", "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.658255939574824, 48.741647562119226 ] } },
{ "type": "Feature", "properties": { "id": "ARTBOU0210021138", "nom": "École de Condé", "descriptif": "", "tel": "", "mail": null, "site_web": "", "sous_cat": "Ecoles", "categorie": "Bâtiments Municipaux", "adresse" : "", "adresse2": "", "cp": "", "commune": "", "photo": null, "source": "" }, "geometry": { "type": "Point", "coordinates": [ 1.660802892618038,48.74123472030836  ] } },

{ "geometry": {"type": "Point", "coordinates": [1.661137603292768,48.741431135298456 ]},"type": "Feature", "properties": {"nom": "Mairie", "descriptif" : "Heures d'ouverture : le  lundi et jeudi de 9h30 à 11h30 et de 14h30 à 17h, le Mardi de 9h30 à 11h30 et de 15h à 17h et le Mercredi de 9h à 12h ", "tel": "33 (0)1.34.87.04.30", "commune": null, "photo": null, "sous_cat": "Bâtiments Publics", "adresse": "" , "categorie": "Bâtiments Municipaux", "source": null, "site_web": null, "mail": "", "cp": "", "id": 245}}
]
};